[fan]
pin = 12
pwm_freq = 100
wait_interval = 5
min_rpm = 1500
max_rpm = 5000

[temperature]
thermal_file = /sys/class/thermal/thermal_zone0/temp
target = 51
hysteresis = 0.5
min_cycles = 3

[fan_curve]
# Each line is a (temperature, duty_cycle) pair.
# The duty cycle will be interpolated between these points.
curve = 
    60: 66
    66: 85
    70: 90
    75: 100
